feat: add projects section
TheGymRwanda/unit8-orange pull request #10
Opened 2022-11-24 17:40 UTC by jacob-js

### Task Description _(❗️Required)_

Added a projects section with links to the individual projects. On hover, a project overview displays on the right side on larger screen whereas on smaller screen, the project overview is displayed under the project link after the user clicks on the link
### Type of Task

- [ ] fix
- [ ] chore
- [x] feat
- [ ] refactor
- [ ] perf
- [ ] docs

### Guidelines

- [x] Does your code follow ES6+ syntax?
- [x] Did you use arrow functional components?
- [x] Did you thoroughly review your code?
- [x] Have you checked if your code does not introduce conflicts in the main codebase?

### Screenshots

### Ticket Link _(❗️Required)_

https://www.notion.so/apeunit/Projects-Section-2bf98fd74be2401cbd23030091158b5e

2022-11-29 12:02 UTC, Lily-Lilian commented on components/sections/Projects/ProjectTitle.jsx
> +        className=" opacity-0 group-hover:opacity-100 transition-opacity duration-300 hidden xl:block mt-[14px]"
Try to use rem and define this specifically by extending the Tailwind CSS configuration and remove this arbitrary values.

2022-11-29 12:56 UTC, Odile078 reviewed
You did a great job, only one thing to consider. Consider creating a data folder outside of the components folder and put in there the ProjectsData file. This is because The helpers folder shouldn't be in the components folder since it is not a component. and also the data folder shouldn't be in helpers since the helpers folder contains files that have functionalities to be used across the project while the data folder contains the data that is going to be needed in the project.

2022-11-29 17:25 UTC, Lily-Lilian submitted a review, later dismissed
LGTM!

2022-11-29 18:36 UTC, Odile078 approved these changes, later dismissed

2022-11-30 10:06 UTC, Odile078 submitted a review, later dismissed

2022-11-30 10:15 UTC, Lily-Lilian submitted a review, later dismissed
Well done!!

2022-11-30 10:21 UTC, alain-kubwayo requested changes
Good job!
```
I left a comment

2022-11-30 10:21 UTC, alain-kubwayo commented on components/sections/Projects/ProjectTitle.jsx
> +      <div className={'transition-opacity duration-300 ' + (active === index ? 'opacity-100': 'opacity-0')}>
I think if you are using double quotes, it's good to stay consistent throughout. You should change single quotes into double quotes to keep consistency.

2022-11-30 10:27 UTC, alain-kubwayo approved these changes
Looks good! 🚀

2022-11-30 10:29 UTC, Lily-Lilian approved these changes

2022-11-30 10:41 UTC, Odile078 approved these changes

2022-11-30 10:43 UTC, merged