#12 Feat: Company Overview Section
TheGymRwanda/unit8-orange pull request #11
Opened 2022-11-29 07:36 UTC by Lily-Lilian

### Task Description _(❗️Required)_

Added Company Overview section for all the breakpoints.
The content on the iPad screen and above is aligned to the right. Clicking on each of the three links render a fresh component with the description.
On the small screen the links are displayed in a column clicking on each link displays the description component right below the link.

### Type of Task

- [ ] fix
- [ ] chore
- [x] feat
- [ ] refactor
- [ ] perf
- [ ] docs

### Guidelines

- [x] Does your code follow ES6+ syntax?
- [x] Did you use arrow functional components?
- [x] Did you thoroughly review your code?
- [x] Have you checked if your code does not introduce conflicts in the main codebase?

### Screenshots

### Ticket Link _(❗️Required)_

https://www.notion.so/apeunit/CompanyOverview-Section-a804d1a5d3ca44fd9bfaff00128c30ea

2022-11-29 12:40 UTC, mercihabam requested changes
## Good job implementing this section

Just some few mistakes I found you have to fix.

2022-11-29 12:40 UTC, mercihabam commented on components/Layout/index.jsx
> +        <CompanyOverview/>
This component must not be imported there, instead it has to go in the home component

2022-11-29 12:40 UTC, mercihabam commented on components/sections/CompanyOverview/Overview.jsx
> +            <div className="">{paragraph?.text}</div>
As the `className` attribute is empty you have to remove it.

2022-11-29 12:40 UTC, mercihabam commented on components/sections/CompanyOverview/index.jsx
> +    },[activeTab])
You have to follow js spacing rules at these statements.

2022-11-29 12:40 UTC, mercihabam commented on components/sections/CompanyOverview/index.jsx
> +                                {activeTabIndex===index&&<div className="pb-8.4">
Spacing ⚠️

2022-11-29 12:40 UTC, jacob-js commented on components/sections/CompanyOverview/index.jsx
> +                                {activeTabIndex===index&&<div className="pb-8.4">
Spacing [⚠️](https://emojipedia.org/warning/)

2022-11-29 12:40 UTC, jacob-js commented on components/sections/CompanyOverview/index.jsx
> +                                <div onClick={()=>{changeActiveTabMobile(index);setActiveTab(item)}} className={"flex items-center justify-between border-b "+ (activeTabIndex===index?"border-purple":
Spacing ⚠️

2022-11-29 12:40 UTC, jacob-js commented on components/sections/CompanyOverview/index.jsx
> +                                <div onClick={()=>{changeActiveTabMobile(index);setActiveTab(item)}} className={"flex items-center justify-between border-b "+ (activeTabIndex===index?"border-purple":
Spacing ⚠️

2022-11-29 12:40 UTC, jacob-js commented on components/sections/CompanyOverview/index.jsx
> +                                    {index===activeTabIndex?(<Motion.div className="absolute mt-0 bottom-1 inset-x-0 h-0.2 bg-purple" layoutId="underline"/>):null}
Spacing ⚠️

2022-11-29 14:36 UTC, clever-cr requested changes
Great job!
I left some reviews check it out

2022-11-29 14:36 UTC, clever-cr commented on components/sections/CompanyOverview/index.jsx
> +            We believe that blockchain technology has the potential to shift financial models as we know them, creating revenue streams that are more sustainable and fair for users. We envision a fut
Remove this empty curly braces to clean codes

2022-11-29 17:14 UTC, clever-cr submitted a review, later dismissed
LGTM!

2022-11-30 06:36 UTC, alain-kubwayo requested changes
Good Job!
```
I left a comment

2022-11-30 06:36 UTC, alain-kubwayo commented on components/sections/CompanyOverview/index.jsx
> +const data = [
The data should be defined in the data folder in the project's root directory.

2022-11-30 12:47 UTC, jacob-js approved these changes

2022-11-30 13:20 UTC, alain-kubwayo approved these changes
Looks great! 🚀

2022-11-30 13:23 UTC, clever-cr approved these changes
Great job!

2022-11-30 13:29 UTC, merged