#15 Feat: Added Footer Component
TheGymRwanda/unit8-orange pull request #13
Opened 2022-11-29 13:15 UTC by clever-cr

### Task Description _(❗️Required)_
Added footer section for desktop, tablet and mobile breakpoints
### Type of Task

- [ ] fix
- [ ] chore
- [x] feat
- [ ] refactor
- [ ] perf
- [ ] docs

### Guidelines

- [ ] Does your code follow ES6+ syntax?
- [ ] Did you use arrow functional components?
- [ ] Did you thoroughly review your code?
- [ ] Have you checked if your code does not introduce conflicts in the main codebase?

### Screenshots

### Ticket Link _(❗️Required)_
https://www.notion.so/apeunit/9c987d9f0f6349ffb7f08c96a12192a3?v=41a7f9534b344a5580c0aae19224d313&p=d71fd22c40f448838b6c66b26c636ca3&pm=s

2022-11-29 13:52 UTC, jacob-js requested changes
## You did well

Just small changes to apply.

2022-11-29 13:52 UTC, jacob-js commented on components/Layout/Footer.jsx
> +          <LinkItem to={"https://de.linkedin.com/company/ape-unit"}>
Don't wrap string inside curly braces, you can replace the `to={""}` with `to=""`

2022-11-29 14:56 UTC, alain-kubwayo requested changes
Good job!
```
See the comment

2022-11-29 14:56 UTC, alain-kubwayo commented on components/Layout/Footer.jsx
> +
Remove this unnecessarily empty line to make your code more readable.

2022-11-29 17:07 UTC, alain-kubwayo submitted a review, later dismissed
Looks good!

2022-11-29 17:28 UTC, Odile078 approved these changes, later dismissed

2022-11-29 17:28 UTC, Odile078 commented on components/Layout/Footer.jsx
> +            Waldemarstraße 38,<br></br> 10999 Berlin
instead of using `<br></br>` use `<br/>`

2022-11-30 09:34 UTC, Lily-Lilian approved these changes, later dismissed

2022-11-30 10:39 UTC, alain-kubwayo approved these changes, later dismissed
Looks good! 🚀

2022-11-30 10:40 UTC, Lily-Lilian submitted a review, later dismissed
LGTM!!

2022-11-30 10:41 UTC, jacob-js approved these changes, later dismissed

2022-11-30 10:43 UTC, Odile078 approved these changes, later dismissed

2022-11-30 10:52 UTC, Lily-Lilian approved these changes

2022-11-30 10:53 UTC, Odile078 approved these changes

2022-11-30 10:56 UTC, jacob-js approved these changes

2022-11-30 10:56 UTC, merged