fixed margin top on mobile
TheGymRwanda/unit8-orange pull request #26
Opened 2022-12-06 10:48 UTC by MugaboDenys

### Task Description _(❗️Required)_
I fixed margin top on mobile screens to 27px(in rems)
### Type of Task

- [x] fix
- [ ] chore
- [ ] feat
- [ ] refactor
- [ ] perf
- [ ] docs

### Guidelines

- [x] Does your code follow ES6+ syntax?
- [x] Did you use arrow functional components?
- [x] Did you thoroughly review your code?
- [x] Have you checked if your code does not introduce conflicts in the main codebase?

### Screenshots

### Ticket Link _(❗️Required)_

https://www.notion.so/apeunit/header-section-mobile-top-margin-4649cd50b0714657b8d31fc28a0f8da6

2022-12-06 13:39 UTC, jacob-js requested changes
## You've made it.

Just on small thing to change, kindly refer to my comment.

2022-12-06 13:39 UTC, jacob-js commented on tailwind.config.js
> +        6.5 : "1.6875rem",
To get the value to use as tailwind key we take the value in pixels divide by 4. for your case is `` 27px / 4 = 6.75``

2022-12-06 13:43 UTC, MugaboDenys commented on tailwind.config.js
> +        6.5 : "1.6875rem",
Thank you @jacob-js

2022-12-12 12:54 UTC, Odile078 approved these changes

2022-12-12 15:36 UTC, alain-kubwayo approved these changes

2022-12-12 17:29 UTC, Lily-Lilian approved these changes
LGTM!

2022-12-20 09:53 UTC, clever-cr approved these changes

2022-12-20 10:53 UTC, jacob-js approved these changes

2022-12-20 10:53 UTC, merged