#08 Ft/header section
TheGymRwanda/unit8-orange pull request #6
Opened 2022-11-23 14:17 UTC by jacob-js

### Task Description _(❗️Required)_

Created the header section & layout component, then included the header inside the layout component and applied the layout for the whole project.

### Type of Task

- [ ] fix
- [ ] chore
- [x] feat
- [ ] refactor
- [ ] perf
- [ ] docs

### Guidelines

- [x] Does your code follow ES6+ syntax?
- [x] Did you use arrow functional components?
- [x] Did you thoroughly review your code?
- [x] Have you checked if your code does not introduce conflicts in the main codebase?

### Screenshots

### Ticket Link _(❗️Required)_

https://www.notion.so/apeunit/Header-Section-6f619c34c8094e3f925a100ce6d434b3

2022-11-23 14:36 UTC, Odile078 commented on components/Layout/Header.jsx
> +            <div className="max-w-201.5">Unit➇ is a pioneering technology company specialing in decentralised technologies that creates end-to-end digital experiences for protocols including <a href=
Instead of using the anchor tag, use the Link component from Next js

2022-11-23 14:38 UTC, Lily-Lilian requested changes

2022-11-23 14:38 UTC, Lily-Lilian commented on components/Layout/Header.jsx
> +import React from 'react'
In the newest versions of React, you don't need to import React ,maybe you can remove this import.

2022-11-23 14:38 UTC, Lily-Lilian commented on components/Layout/index.jsx
> +import React from 'react'
Same here!

2022-11-23 14:42 UTC, Odile078 commented on components/Layout/Header.jsx
> +        <div className='py-12 flex-col lg:flex-row gap-5 flex text-2xl justify-between'>
You forgot to add the font size for the small screens

2022-11-23 14:45 UTC, Odile078 commented on components/Layout/Header.jsx
> +        <div className='py-12 flex-col lg:flex-row gap-5 flex text-2xl justify-between'>
You forgot to add the custom line-height.

2022-11-23 14:48 UTC, Odile078 reviewed
Good job but there are few changes you need to add.

2022-11-23 15:00 UTC, alain-kubwayo reviewed
Good job! You should apply the changes requested by @Odile078 and @Lily-Lilian

2022-11-23 15:18 UTC, clever-cr requested changes

2022-11-23 15:18 UTC, clever-cr commented on components/Layout/Header.jsx
> +            <div className="">Ape Unit</div>
You should remove this  class if you don't use it

2022-11-24 09:07 UTC, alain-kubwayo requested changes
Good job. 
``` 
You should first resolve the conflicts in the LinkItem.jsx component

2022-11-24 09:13 UTC, alain-kubwayo approved these changes, later dismissed
Well-done! 🚀

2022-11-24 09:19 UTC, clever-cr approved these changes, later dismissed
LGTM!

2022-11-24 09:29 UTC, Odile078 submitted a review, later dismissed

2022-11-24 10:00 UTC, Odile078 approved these changes

2022-11-24 10:45 UTC, Lily-Lilian approved these changes

2022-11-24 10:47 UTC, alain-kubwayo approved these changes
Great 🚀

2022-11-24 10:47 UTC, merged