#07 Feat: Add Tag Component
TheGymRwanda/unit8-orange pull request #7
Opened 2022-11-23 14:35 UTC by clever-cr

### Task Description _(❗️Required)_

Created tag component to be used in other sections
### Type of Task

- [ ] fix
- [ ] chore
- [x] feat
- [ ] refactor
- [ ] perf
- [ ] docs

### Guidelines

- [x] Does your code follow ES6+ syntax?
- [x] Did you use arrow functional components?
- [x] Did you thoroughly review your code?
- [x] Have you checked if your code does not introduce conflicts in the main codebase?

### Screenshots

### Ticket Link _(❗️Required)_
https://www.notion.so/apeunit/Tag-component-50ec6069c87c4157b816921768a5fa19

2022-11-23 14:58 UTC, jacob-js commented on components/ui/Tag.jsx
> +      <p className="font-neuf text-lg text-primaryGray-400 font-normal -tracking-wide bg-primaryGray-200 rounded-base px-2.5 py-sm  w-fit">
`font-normal` className is not actually needed since it doesn't change anything on the text, it's good to remove it.

2022-11-23 15:00 UTC, jacob-js requested changes
## Congrats for what you've done

Just on thing to have a look on, kindly refer to the comment I left.

2022-11-23 15:18 UTC, Odile078 commented on components/ui/Tag.jsx
> +      <p className="font-neuf text-lg text-primaryGray-400 font-normal -tracking-wide bg-primaryGray-200 rounded-base px-2.5 py-sm  w-fit">
You forgot to add a custom line-height and the font-size for the small screens.

2022-11-23 17:43 UTC, alain-kubwayo requested changes
Good job!
```
Minor adjustments and you're good to go.

2022-11-23 17:43 UTC, alain-kubwayo commented on components/ui/Tag.jsx
> +    </div>
You introduced an unnecessary tag. `<div>` doesn't have any semantic meaning to your code and your code should still work without the outer div.

2022-11-23 17:43 UTC, alain-kubwayo commented on components/ui/Tag.jsx
> +      <p className="font-neuf text-lg text-primaryGray-400  -tracking-wide  bg-primaryGray-200  rounded-base  px-2.5  py-sm w-fit">
The padding should be adjusted according to the design like so, `padding: 3px 10px;`

2022-11-23 17:54 UTC, alain-kubwayo approved these changes
Looks great! 🚀

2022-11-23 18:33 UTC, Odile078 approved these changes
LGTM

2022-11-24 09:05 UTC, Lily-Lilian approved these changes

2022-11-24 09:22 UTC, jacob-js approved these changes

2022-11-24 09:23 UTC, merged