#05 Feat: Add Title Component
TheGymRwanda/unit8-orange pull request #8
Opened 2022-11-23 14:45 UTC by alain-kubwayo

### Task Description _(❗️Required)_

In this PR, a title component to be reused as a heading for most sections was created. It is left-aligned across all screen devices.

### Type of Task

- [ ] fix
- [ ] chore
- [x] feat
- [ ] refactor
- [ ] perf
- [ ] docs

### Guidelines

- [x] Does your code follow ES6+ syntax?
- [x] Did you use arrow functional components?
- [x] Did you thoroughly review your code?
- [x] Have you checked if your code does not introduce conflicts in the main codebase?

### Screenshots

### Ticket Link _(❗️Required)_

https://www.notion.so/apeunit/Title-component-3ce7553d7a1b4c7da12dbedaf9da5893

2022-11-23 15:05 UTC, jacob-js requested changes

2022-11-23 15:05 UTC, jacob-js commented on components/ui/Title.jsx
> +const Title = ({ name }) => <h3 className="text-2xl leading-7 text-primaryGray-300 -tracking-tighter">{ name }</h3>
The font size change according to the screen the text is being displayed on, make sure you take it into consideration.

2022-11-24 08:22 UTC, Lily-Lilian approved these changes
LGTM!

2022-11-24 09:12 UTC, clever-cr approved these changes
Great job LGTM!

2022-11-24 09:30 UTC, jacob-js approved these changes

2022-11-24 09:31 UTC, merged